### ISSUE TITLE
Missing shader files

### ISSUE THREAD

**Issue by richardba** [sp4cerat/Planet-LOD#1]
shader/SkinScaled/tcs.txt
shader/SkinScaled/tes.txt
shader/SkinScaled/geo.txt
shader/SkinScaledInner/tcs.txt
shader/SkinRepeated/tcs.txt
shader/SkinRepeated/tes.txt
shader/SkinRepeated/geo.txt

are missing

**Comment by sp4cerat** [comment]
they are not missing. the shader class just tries to load all available and links them.
